const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  search:            (p) => ipcRenderer.invoke('search', p),
  chat:              (p) => ipcRenderer.invoke('chat', p),
  login:             (p) => ipcRenderer.invoke('login', p),
  register:          (p) => ipcRenderer.invoke('register', p),
  getMe:             (t) => ipcRenderer.invoke('get-me', t),
  getToken:          ()  => ipcRenderer.invoke('get-token'),
  saveToken:         (t) => ipcRenderer.invoke('save-token', t),
  clearToken:        ()  => ipcRenderer.invoke('clear-token'),
  getServerUrl:      ()  => ipcRenderer.invoke('get-server-url'),
  saveServerUrl:     (u) => ipcRenderer.invoke('save-server-url', u),
  saveSearch:        (t, d) => ipcRenderer.invoke('save-search', t, d),
  loadSavedSearches: (t) => ipcRenderer.invoke('load-saved-searches', t),
  deleteSavedSearch: (t, id) => ipcRenderer.invoke('delete-saved-search', t, id),
  pipeline:          (method, token, id, data) => ipcRenderer.invoke('pipeline', method, token, id, data),
  openExternal:      (u) => ipcRenderer.invoke('open-external', u),
  getVersion:        ()  => ipcRenderer.invoke('get-version'),
  checkUpdates:      ()  => ipcRenderer.invoke('check-updates'),
  installUpdate:     ()  => ipcRenderer.invoke('install-update'),
  onLogout:          (callback) => ipcRenderer.on('logout', callback),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', callback),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', callback),
});
